### ISSUE TITLE
Saving transform AFTER move makes reconciliation smoother

### ISSUE THREAD

**Issue by oMarcelo92** [lucasmontec/UnetCharacterController#4]
Investigate why that happens.

**Comment by lucasmontec** [comment]
The transform wasn't beeing save but it was beeing referenced throughout the entire reconciliation list. I have changed all entries to store positions and rotations instead of the transform. Now the server seems to have some problems calculating some times BUT the movement never been so smooth.

**Comment by lucasmontec** [comment]
Doesn't make any sense.
